 platform :ios, '9.0'

target 'Instagram_Clone' do
  use_frameworks!

pod 'Appirater'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Core'

end
